name: aq_tools
description: Set of tools we use here at AQuadic Softwars.
version: 0.0.4
homepage: "https://AQuadic.com"

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
