name: aq_tools
description: Set of tools we use here at AQuadic Softwars.
version: 0.1.2+12
homepage: "https://AQuadic.com"

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.9.0"

dependencies:
  flutter:
    sdk: flutter
  quiver:
  convert:
  easy_localization:

dev_dependencies:
  build_runner: ^2.4.8 # flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^6.7.1

flutter:
