name: aq_tools
description: Set of tools we use here at AQuadic Softwares.
version: 0.1.3+13
homepage: "https://AQuadic.com"

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.9.0"

dependencies:
  flutter:
    sdk: flutter
  quiver:
  convert:
  easy_localization:

flutter:
